apiVersion: v1 
kind: Service
metadata:
  name: http-hello-service
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 80
    protocol: TCP
  selector:
    app: hello-service
  type: LoadBalancer
